Health Economic Form
effect-trial/effect-edc pull request #16
Opened 2022-06-09 11:05 UTC by frdrckaman

2022-06-27 15:25 UTC, JonathanWillitts requested changes
Thanks Freddie,

I've made some suggestions to take a look at.  Please could you also?

- [x] update line 220 of `effect_subject\choices.py` to `Relative or others paying for drug`
- [ ] rename `health_economics.py` to `health_economics_event.py`
- [ ] rename `health_economics_baseline.py` to `health_economics.py`

2022-06-27 15:25 UTC, JonathanWillitts commented on effect_subject/models/health_economics.py
> +        choices=CHILDCARE_CHOICES,
Childcare choices has NA option, which I don't think is applicable for this question.  I suggest creating a separate set of choices, with NA omitted.

2022-06-27 15:33 UTC, JonathanWillitts commented on effect_subject/models/health_economics_baseline_termination.py
> +        verbose_name = "Health Economics Baseline"
```suggestion
        verbose_name = "Health Economics"
```

2022-07-05 04:08 UTC, frdrckaman commented on effect_lists/list_data.py
> +    ],
I didnt write this, I just reuse it so my concern is when I rearrange it it my messup on other place where it has been used

2022-07-05 23:18 UTC, JonathanWillitts requested changes
Thanks for the prompt changes.

There are still a couple of things:

- [ ] the list data still needs sorting
- [ ] the renaming process doesn't seem to be finished.  i.e. the class names need renaming to match the (new) module names.  Everything should be either HealthEconomicsXyz, or HealthEconomicsEventXyz.  I've made a few suggestions to get you started 
- [ ] transport_used should be an m2m field
- [ ] can you make sure the tests are all passing in GitHub Actions (on your fork)?

2022-07-06 08:44 UTC, JonathanWillitts commented on effect_subject/admin/health_economics_admin.py
> -
There needs to be an associated form for the HealthEconomics model

2022-07-20 10:36 UTC, merged

2022-07-20 10:38 UTC, JonathanWillitts commented
Thanks Freddie, 

I'm merging this into a branch to review/make some final changes, with a view to including it into develop.  

I'll update you once it's finalised.